### PR TITLE
Updated large ancient map to latest build

### PR DESCRIPTION
**Pull request by esampson**

### CODE REVIEW

**Comment by ftomassetti** [comment]
I would first merge the new rivers (about to do that) and then regenerate this image. Does that work for you?

**Comment by esampson** [comment]
Sure. I'll need to regenerate the other images as well.

**Comment by esampson** [comment]
Ok. All images have been regenerated with the latest build.

**Comment by ftomassetti** [comment]
I love the mountain ranges in the large ancient map

**Pull request merged**
