### PR TITLE
Updated old images to output from current software revision.

### PR DESCRIPTION
**Pull request by esampson**
Added some new images for documentation.

### CODE REVIEW

**Comment by ftomassetti** [comment]
I would avoid spaces in filenames. It sounds silly but sooner or later they lead to problems :)

**Comment by ftomassetti** [comment]
And then we should remember to use those images in the README (the ones with the name changed)

**Comment by esampson** [comment]
Yes. I plan to use those images in the read me. I just need to get them staged first. :)

**Comment by ftomassetti** [comment]
oh, you renamed them. It looks good to me then. Thanks

**Pull request merged**
