### PR TITLE
Added biome and Holdridge images for documentation.

### PR DESCRIPTION
**Pull request by esampson**
After this pull is merged I will be able to create documentation explaining biome placement, temperature and humidity zones, scatter plots and the temperature/humidity curve, and the new command line options related to all of these.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Beautiful images!

**Comment by psi29a** [comment]
Did you create these yourself? If not, where did you get them? Do we have permission to use them? If so, under what license?

**Comment by esampson** [comment]
I created them both.

**Comment by psi29a** [comment]
Awesome job!  What license would you like to apply them under?
I would suggest one of the licenses from here: https://creativecommons.org/

**Comment by esampson** [comment]
Whatever license we are applying to the document as a whole. I don't see any reason to increase anyone's confusion with a separate license to the images I created.

**Comment by psi29a** [comment]
Roger that. We don't actually have anything, but we should decided that. What do you think @ftomassetti ?

I'm for CC-BY-SA: https://creativecommons.org/licenses/by-sa/4.0/

however if someone else has another opinion...

**Comment by ftomassetti** [comment]
I would say the license would be perfect for the image but for the text I would go for something even more liberal: for example if someone would cite an excerpt from the manual with this license it would be forced to release the whole article, post or book under the same license and that could be not always possible. I agree that it could be simpler to go for just one license for the images and the book: in that scenario I would prefer the most liberal form, unless @esampson prefers otherwise (so far @esampson is the one who provided more value to the manual).

Would be http://creativecommons.org/publicdomain/ too much? From my point of view it would be nice to include just the obbligation to cite the project and for the rest I would be for giving all the freedom possible.

Just my thought but I do not feel strong about this.

**Comment by psi29a** [comment]
I'm OK with CC-0, but that is really public domain. I'm cool with it if @esampson is cool, but then people use it without citing the author nor giving attribution.

If he would still like to be cited for his work, then CC-BY is also OK:
https://creativecommons.org/licenses/by/4.0/

This means that you can still use it in other works and adapted/shared into another incense but forces the user to cite and give attribution to the original author and those that have adapted it.

**Comment by ftomassetti** [comment]
This one seems perfect to me. Thanks Bret!

**Pull request merged**
