### PR TITLE
Regenerated some worlds using the numpy-branch.

### PR DESCRIPTION
**Pull request by tcld**
I hope this is what I was supposed to do.

### CODE REVIEW

**Comment by tcld** [comment]
I am not sure if this is done correctly or not. Right now the tests on my system don't go through, so I will have to check some more things. Hold on.
(And if there are more files to update, please tell me.)

EDIT: I thought I generated a pickle-file (28070), but for some reason it is being read with protobuf - and that fails. Do you have any hints? I used the following parameters:
`worldengine --output-dir=. --seed=28070 --step=full --height=100 --width=100 --number-of-plates=5 --rivers world`

EDIT: According to drawing_functions_test.py it should be a protobuf-file. xP

**Comment by tcld** [comment]
Now I am left with a dozen blessed_pixel-errors. How do I deal with those? I assume I have to replace the images, too. But since they are named a bit strange I am not sure.

To clarify: Before I updated the world I had one blessed-pixel error. Hence I think that it is not the drawing functions but the world generation that changed (probably due to the change to the seeding done here:
https://github.com/Mindwerks/worldengine/commit/2adb20af6d60ddb2d9380a2c50b95ab19346c5fb )

**Comment by tcld** [comment]
Ok, I updated the images.

The pickle-save is left untouched and that is now the cause for the only failed test that remains. But since it differs depending on the used version of Python there wouldn't be much use in regenerating it anyway. (Because then other peoples tests would fail.)

```
================================================================================================================= FAILURES ==================================================================================================================
____________________________________________________________________________________________ TestDrawingFunctions.test_draw_ancient_map_factor1 _____________________________________________________________________________________________

self = <tests.drawing_functions_test.TestDrawingFunctions testMethod=test_draw_ancient_map_factor1>

    def test_draw_ancient_map_factor1(self):
>       w_large = World.from_pickle_file("%s/seed_48956.world" % self.tests_data_dir)

tests/drawing_functions_test.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'worldengine.world.World'>, filename = '/media/tcl/Software/Code/UnrealProjects/Worldengine/master/worldengine-data/tests/data/seed_48956.world'

    @classmethod
    def from_pickle_file(cls, filename):
        with open(filename, "rb") as f:
>           return pickle.load(f)
E           UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 3: ordinal not in range(128)

worldengine/world.py:50: UnicodeDecodeError
=================================================================================================== 1 failed, 39 passed in 17.60 seconds ====================================================================================================
```

**Comment by tcld** [comment]
Summary: I think I am done with this. It was a bit difficult to figure out what to do, though.

**Comment by tcld** [comment]
I noticed that I regenerated plates_279.world, which is actually a pickle-file. So I guess that file would break Python 2-compatibility.

A possible solution is suggested here:
https://github.com/Mindwerks/worldengine/issues/139#issuecomment-149460972

**Comment by psi29a** [comment]
Yup, two problems. 
1) Python2 vs. Python3 pickle format
2) Old pickle formats (without numpy)

We solve the 1st one by writting tests specific to python version that created the pickle file.

The second one requires that we replace all the old pickle worlds and images in worldengine-data.

**Comment by tcld** [comment]
The tests-problem seems to be easy to solve. I can generate the Python 3-worlds, too.

**Comment by psi29a** [comment]
So once this branch is merged, the tests in worldengine will work again?

Also I noticed this when looking at the "files changed": tests/images/temperature_28070.png
The old way seems to have more... chaos in it instead of just stripes. Was this the intention?

**Comment by tcld** [comment]
I noticed that, too. I had not changed anything about the temperature-file yet, so I am not sure why it looks so different. Maybe it is just the differently-shaped world that is responsible?

**Comment by tcld** [comment]
The temperature image here also looks a lot noisier:
https://github.com/Mindwerks/worldengine-data/blob/master/images/examples/world_seed_1_temperature.png

That can't be a coincidence, can it? Did something about the temperature-algorithm change within the last ~4 months? Are my changes responsible for this? (I don't think I ever generated a map like that, though. Not even with the release-version. I might have to go back and check that.)

**Comment by ftomassetti** [comment]
Could that depends on the elevation? I think it affects the temperature

**Comment by tcld** [comment]
Yes, it does. Flat areas might influence it. However, when I ran the (slightly modified) temperature-generation here https://github.com/Mindwerks/worldengine/pull/143 all of the outputs I got were much less random than the one linked to above.

**Comment by psi29a** [comment]
So... merge this when worldengine-data is ready?

**Comment by psi29a** [comment]
We'll get back to this later. I'm happy to merge this to get our tests back in order. :)

You OK with this @ftomassetti ?

**Comment by ftomassetti** [comment]
Yes, go on!

**Pull request merged**
